@startuml

component "Sensor Framework" as SensorFramework

interface "\nWebsockets" as SensorInterface
SensorFramework - SensorInterface

component "RoboArmController"
SensorInterface )- RoboArmController

component "Machine Learning Framework" as MLFramework
RoboArmController --> MLFramework: uses

component RoboArmSimulation

interface "\nSockets" as RoboArmInterface
RoboArmController -( RoboArmInterface
RoboArmInterface - RoboArmSimulation


@enduml
